import type { Artwork } from "./types";

/**
 * Local fallback content used whenever Sanity isn't configured yet
 * (no PUBLIC_SANITY_PROJECT_ID set). Lets the site run and look complete
 * before the CMS is connected. Swap for real pieces in Sanity Studio —
 * this file is never touched by the CMS.
 */
export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: "mock-1",
    slug: "study-in-graphite-i",
    title: "Study in Graphite I",
    year: "2024",
    medium: "Graphite on paper",
    dimensions: "11 × 14 in",
    description:
      "A quiet study exploring light and form. Sample placeholder — replace with real work in Sanity Studio.",
    price: 220,
    currency: "USD",
    status: "available",
    buyLink: "",
    featured: true,
    size: "wide",
    image: { url: "/cats.webp", alt: "Placeholder artwork", width: 1024, height: 622 },
    order: 1,
  },
  {
    id: "mock-2",
    slug: "left-facing-study",
    title: "Left-Facing Study",
    year: "2024",
    medium: "Graphite on paper",
    dimensions: "9 × 12 in",
    description: "Sample placeholder — replace with real work in Sanity Studio.",
    price: 180,
    currency: "USD",
    status: "available",
    buyLink: "",
    size: "half",
    image: { url: "/cat-left.webp", alt: "Placeholder artwork", width: 736, height: 812 },
    order: 2,
  },
  {
    id: "mock-3",
    slug: "right-facing-study",
    title: "Right-Facing Study",
    year: "2023",
    medium: "Graphite on paper",
    dimensions: "9 × 12 in",
    description: "Sample placeholder — replace with real work in Sanity Studio.",
    price: 180,
    currency: "USD",
    status: "sold",
    size: "half",
    image: { url: "/cat-right.webp", alt: "Placeholder artwork", width: 876, height: 580 },
    order: 3,
  },
  {
    id: "mock-4",
    slug: "untitled-study",
    title: "Untitled Study",
    year: "2023",
    medium: "Charcoal on paper",
    dimensions: "8 × 10 in",
    description: "Sample placeholder — replace with real work in Sanity Studio.",
    status: "not-for-sale",
    size: "third",
    image: { url: "/cats.webp", alt: "Placeholder artwork", width: 1024, height: 622 },
    order: 4,
  },
  {
    id: "mock-5",
    slug: "untitled-study-ii",
    title: "Untitled Study II",
    year: "2023",
    medium: "Graphite on paper",
    dimensions: "8 × 10 in",
    description: "Sample placeholder — replace with real work in Sanity Studio.",
    price: 150,
    currency: "USD",
    status: "available",
    buyLink: "",
    size: "third",
    image: { url: "/cat-left.webp", alt: "Placeholder artwork", width: 736, height: 812 },
    order: 5,
  },
  {
    id: "mock-6",
    slug: "untitled-study-iii",
    title: "Untitled Study III",
    year: "2022",
    medium: "Ink on paper",
    dimensions: "8 × 10 in",
    description: "Sample placeholder — replace with real work in Sanity Studio.",
    price: 150,
    currency: "USD",
    status: "available",
    buyLink: "",
    size: "third",
    image: { url: "/cat-right.webp", alt: "Placeholder artwork", width: 876, height: 580 },
    order: 6,
  },
];
